---
- name: Install apache
  hosts: web
  become: true
  tasks:
    - name: Update the apt-get
      apt: 
        update_cache: yes

    - name: Create a directory if it does not exist
      file:
        path: "{{ website_path}}"
        state: directory

    - name: Copy new index.html file
      copy:
        src: /var/www/html/index.html
        dest: "{{ website_path }}/index.html"
        remote_src: yes

    - name: Copy configuration file for apache 
      copy:
        src: /etc/apache2/sites-available/000-default.conf
        dest: /etc/apache2/sites-available/Nisha.conf
        remote_src: yes

    - name: Enable site for Nisha.conf
      command:
        a2ensite Nisha.conf

    - name: Disable site for Nisha.conf
      command:
        a2dissite 000-default.conf

    - name: Restart apache server
      service:
        name: apache2
        state: restarted



